In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("household_power_consumption.txt", sep=';', low_memory=False)

In [3]:
df.columns

Index(['Date', 'Time', 'Global_active_power', 'Global_reactive_power',
       'Voltage', 'Global_intensity', 'Sub_metering_1', 'Sub_metering_2',
       'Sub_metering_3'],
      dtype='object')

In [4]:
df.to_csv("household_power_consumption_clean.csv", index=False)

In [5]:
df.head()

,Date,Time,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3
0,16/12/2006,17:24:00,4.216,0.418,234.840,18.400,0.000,1.000,17.0
1,16/12/2006,17:25:00,5.360,0.436,233.630,23.000,0.000,1.000,16.0
2,16/12/2006,17:26:00,5.374,0.498,233.290,23.000,0.000,2.000,17.0
3,16/12/2006,17:27:00,5.388,0.502,233.740,23.000,0.000,1.000,17.0
4,16/12/2006,17:28:00,3.666,0.528,235.680,15.800,0.000,1.000,17.0

In [6]:
df.shape

(2075259, 9)

In [7]:
df.columns

Index(['Date', 'Time', 'Global_active_power', 'Global_reactive_power',
       'Voltage', 'Global_intensity', 'Sub_metering_1', 'Sub_metering_2',
       'Sub_metering_3'],
      dtype='object')

In [8]:
df.tail()

,Date,Time,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3
2075254,26/11/2010,20:58:00,0.946,0.000,240.430,4.000,0.000,0.000,0.0
2075255,26/11/2010,20:59:00,0.944,0.000,240.000,4.000,0.000,0.000,0.0
2075256,26/11/2010,21:00:00,0.938,0.000,239.820,3.800,0.000,0.000,0.0
2075257,26/11/2010,21:01:00,0.934,0.000,239.700,3.800,0.000,0.000,0.0
2075258,26/11/2010,21:02:00,0.932,0.000,239.550,3.800,0.000,0.000,0.0

In [9]:
df.dtypes

Date                      object
Time                      object
Global_active_power       object
Global_reactive_power     object
Voltage                   object
Global_intensity          object
Sub_metering_1            object
Sub_metering_2            object
Sub_metering_3           float64
dtype: object

In [10]:
df.isna().sum()

Date                         0
Time                         0
Global_active_power          0
Global_reactive_power        0
Voltage                      0
Global_intensity             0
Sub_metering_1               0
Sub_metering_2               0
Sub_metering_3           25979
dtype: int64

In [11]:
df.describe()

       Sub_metering_3
count    2.049280e+06
mean     6.458447e+00
std      8.437154e+00
min      0.000000e+00
25%      0.000000e+00
50%      1.000000e+00
75%      1.700000e+01
max      3.100000e+01

In [13]:
df.info

<bound method DataFrame.info of                Date      Time Global_active_power Global_reactive_power  \
0        16/12/2006  17:24:00               4.216                 0.418
1        16/12/2006  17:25:00               5.360                 0.436
2        16/12/2006  17:26:00               5.374                 0.498
3        16/12/2006  17:27:00               5.388                 0.502
4        16/12/2006  17:28:00               3.666                 0.528
...             ...       ...                 ...                   ...
2075254  26/11/2010  20:58:00               0.946                 0.000
2075255  26/11/2010  20:59:00               0.944                 0.000
2075256  26/11/2010  21:00:00               0.938                 0.000
2075257  26/11/2010  21:01:00               0.934                 0.000
2075258  26/11/2010  21:02:00               0.932                 0.000

         Voltage Global_intensity Sub_metering_1 Sub_metering_2  \
0        234.840           18.400          0.000          1.000
1        233.630           23.000          0.000          1.000
2        233.290           23.000          0.000          2.000
3        233.740           23.000          0.000          1.000
4        235.680           15.800          0.000          1.000
...          ...              ...            ...            ...
2075254  240.430            4.000          0.000          0.000
2075255  240.000            4.000          0.000          0.000
2075256  239.820            3.800          0.000          0.000
2075257  239.700            3.800          0.000          0.000
2075258  239.550            3.800          0.000          0.000

         Sub_metering_3
0                  17.0
1                  16.0
2                  17.0
3                  17.0
4                  17.0
...                 ...
2075254             0.0
2075255             0.0
2075256             0.0
2075257             0.0
2075258             0.0

[2075259 rows x 9 columns]>